### ISSUE TITLE
[Circle-OpSelector] How to 'run' circle model?

### ISSUE THREAD

**Issue by parkeunsang** [Samsung/ONE#7606] opened 2021-09-04 13:17 UTC
I'm developing a `Circle-OpSelector` in team COSMOS. #7596  
And I want to **test a validation of circle file(model)** that is selected by Circle-OpSelector.
If the selected circle file is odd, error will be caused.(for example, layer1 and layer2 are connected but if layer1's output dimension and layer2's input dimension are different, this model can't run)
So I want to '**run**' the selected circle model to check a validation. And 'run' means '**get output data from input data through circle model**'.
I think `gen_golden` can do this role but in my opinion, it is not sufficient for test because it just run model using tensorflow(not certain).
So I want to know another method to run a circle model or method for validation check of circle models. Thanks

**Comment by glistening** [comment] 2021-09-06 03:44
As I told last week, use `tflite2nnpkgtc`, which runs `model2nnpkg`, `gen_golden` internally, then run nnpkgtc with `nnpkg_test.sh`. You may refer to https://github.com/Samsung/ONE/issues/332#issuecomment-619770684.

**Comment by mhs4670go** [comment] 2021-09-06 03:56
I think it would be more convenient if you use the module in compiler because it is easier to integrate with `circle-opselector` tests.

There is [luci-interpreter](https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-interpreter) that can runs `circle` model. Since the module is library, it needs [driver](https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-eval-driver). And you can refer to [luci-value-test](https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-value-test) that has a script to use its driver.

**Comment by glistening** [comment] 2021-09-06 05:05
> I think it would be more convenient if you use the module in compiler because it is easier to integrate with `circle-opselector` tests.
> 
> There is [luci-interpreter](https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-interpreter) that can runs `circle` model. Since the module is library, it needs [driver](https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-eval-driver). And you can refer to [luci-value-test](https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-value-test) that has a script to use its driver.

It may depends on. I don't know much about `luci-interpreter`, also I cannot find much information from the guide you've given. The first link to `driver` has the root of source code. The second link has only text description, no how to. Also, how much `luci-interpreter` covers operators? For example, is it possible to run `while` operator?

Also, what do you mean by "easier to integrate with `circle-opselector`?" Do you want `circle-opselector` integrated with `luci-interpreter`? I was thinking of running `circle` model to test manually, I don't think it will be run in CI.

**Comment by mhs4670go** [comment] 2021-09-06 05:53
> I don't know how to build and run `luci-value-test`.

It can be run after compiler modules are built(https://github.com/Samsung/ONE/blob/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/docs/howto/how-to-build-compiler.md). And, when it comes to how to implement codes with `luci-interperter`, refering to [luci-value-test](https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-value-test) is enough because `luci_eval_verifier.py` script is very intuitive. 

> Also, how much `luci-interpreter` covers operators? For example, is it possible to run `while` operator?

Yes. You can see the support operators in https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-interpreter/src/kernels.

> Also, what do you mean by "easier to integrate with `circle-opselector`?" Do you want `circle-opselector` integrated with `luci-interpreter`? I was thinking of running `circle` model to test manually, I don't think it will be run in CI.

It means that it is easier to integrate with the existing ctest. I recommends the modules in compiler are tested in CI automatically, which will be helpful in the future. But if you insist, it could be postponed.

**Comment by glistening** [comment] 2021-09-06 06:23
@mhs4670go Thank you for further information. 

But I still don't find how to use before investigating several sources under aforementioned tools though you're saying it is very _intuitive_. Here are some questions:

From `luci-value-test/README.md`:

> Step 1: Generate tflite files and circle files from TFLite recipes (listsed in test.lst). "TFLite recipe" -> tflchef -> "tflite file" -> tflite2circle -> "circle file"

**Q1.**  I think we don't need to know about `TFLite recipe`. The selected tflite and circle model will be inputs. Is it right?

> Step 2: Run TFLite interpreter and luci-interpreter for the generated tflite and circle, respectively. (with the same input tensors filled with random values) circle file -> luci-interpreter -------> Execution result 1 tflite file -> TFLite interpreter -----> Execution result 2

TODO: This paragraphs requires additional line-breaks to show properly. I will create PR.

> Step 3: Compare the execution result 1 and 2. The result must be the same.

**Q2.** How to compare? I am reading https://github.com/Samsung/ONE/blob/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-value-test/evalverify.sh#L7-L10

But I don't fully understand how to run. Is there some example?

> https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-interpreter/src/kernels.

**Q3.** It has `While.cpp` and `While.h`. Does `luci-interpreter` support `while` operator?

@parkeunsang and COSMOS members, please leave question about `luci-...` way.

**Comment by glistening** [comment] 2021-09-06 06:26
@mhs4670go Thank you for further information. 

But I still don't find how to use before investigating several sources under aforementioned tools though you're saying it is very _intuitive_. Here are some questions:

From `luci-value-test/README.md`:

> Step 1: Generate tflite files and circle files from TFLite recipes (listsed in test.lst). "TFLite recipe" -> tflchef -> "tflite file" -> tflite2circle -> "circle file"

**Q1.**  I think we don't need to know about `TFLite recipe`. The selected tflite and circle model will be inputs. Is it right?

> Step 2: Run TFLite interpreter and luci-interpreter for the generated tflite and circle, respectively. (with the same input tensors filled with random values) circle file -> luci-interpreter -------> Execution result 1 tflite file -> TFLite interpreter -----> Execution result 2

This paragraphs is shown in one line. I've updated the document. Please see #7608.

> Step 3: Compare the execution result 1 and 2. The result must be the same.

**Q2.** How to compare? I am reading https://github.com/Samsung/ONE/blob/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-value-test/evalverify.sh#L7-L10

But I don't fully understand how to run. Is there some example?

> https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-interpreter/src/kernels.

**Q3.** It has `While.cpp` and `While.h`. Does `luci-interpreter` support `while` operator?

@parkeunsang and COSMOS members, please leave question about `luci-...` way.

**Comment by kevin622** [comment] 2021-09-06 07:11
Thank you @mhs4670go  and @glistening ! After reviewing the descriptions and explanations of both operations(`luci-value-test` and `nnpckgtc`), I am starting to see that there are some differences in the purpose of the two.

- `luci-value-test` is to compare a `tflite` file and a `circle` file. The purpose of this _test_ is to see if `tflite2circle` has caused any changes to the structure of the model.
- On the other hand, `nnpckgtc` is to compare the output of a model(especially, a `tflite` model) from the compiler step to the output from the same model but from the runtime step. The purpose of this _test_ is to see whether the __packager__ and the __runtime__ has caused any changes to the structure of the model from the __compiler__.

Under this understanding, it seems that the best way to conduct testing for a `Circle-OpSelector` is using `nnpckgtc` as such steps;
1. Prepare a `tflite` model.
2. Create a `circle` version of that `tflite` model using 'tflite2circle`.
3. Create a `tflite` subgraph using `select_operator.py`.
4. Create a `circle` subgraph using `Circle-OpSelector`.
5. Run `nnpckgtc` with input as the `tflite` subgraph to get the golden value and the package.
6. Modify the __package__ so that it contains the `circle` subgraph, not the `tflite` subgraph. This step is due to the fact that the circle model can't be an input of `nnpckgtc`.
7. Run the __package__ in __runtime__ to get the output of the `circle` subgraph package, with the same input used for getting the golden value.
8. Compare the golden value with the __runtime__ output.

Please correct me if I'm misunderstanding the purpose of the files, and feel free to let us know if there are any problems is our step.

**Comment by glistening** [comment] 2021-09-06 07:39
@kevin622  I think step 1 ~ step 4 will be same. It is done before running the models.

```
(1) tflite --(select_operator.py)--> (3) selected tflite
 |
 | (tflite2circle)
 V
(2) circle --(circle_opselector) --> (4) selected circle
```

For step 5 ~ step 8, we have two choices for executing: `luci-xxx` (from compiler) or `nnpkg-xxx` (from runtime).
Both do same things fundamentally. 

```
(3) tflite --(execute using tflite_interpreter) --> (5-1) generated random input and (5-2) output from tflite_interpreter
(4) circle --(execute using either luci-interpreter or one-runtime with input of (5-1) ) --> (7) output
```

Then, do Step 8. That is, Compare (5-2) and (7).

`onert` has more operator coverage and tested more.
On the other hands, `luci-xxx` is easier to integrate test in CI later if necessary.

Please choose which takes less time at this moment.
It should not take a long time to switch from one to another because they are fundamentally same when we've finished the `opselector` itself.

**Comment by mhs4670go** [comment] 2021-09-06 08:37
@glistening 

> **Q1.**  I think we don't need to know about `TFLite recipe`. The selected tflite and circle model will be inputs. Is it right?

There is no need to know about `TFLite recipe` to use only `circle-interpreter`. But, if you implement test related modules, you should. Because all the test resources in compiler is from the recipe.

**Q2.** How to compare? I am reading 

Please see https://github.com/Samsung/ONE/blob/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-value-test/luci_eval_verifier.py file. The comments are explaining each step.

```bash
# Build TFLite interpreter.
..
# Generate random input data.
..
# Do inference
..
# Execute luci interpreter.
..
# Compare the results.
..
```

> **Q3.** It has `While.cpp` and `While.h`. Does `luci-interpreter` support `while` operator?

Yeap. @jinevening Is it okay for us to say `luci-interpreter` fully supports `while` op?


@kevin622 

> The purpose of this _test_ is to see if `tflite2circle` has caused any changes to the structure of the model.

> `luci-value-test` validates luci IR graph model file (.circle)

Please note that the module name is `value test` and see above comments. Whatever the structure of the model file, this module checks the value of the actual output.

> 3. Create a `tflite` subgraph using `select_operator.py`.

If you want to go with `tflite2nnpkgtc`, the subgraphs to compare should be created by tensorflow library itself rather than `select_operator.py`. Because the test should be independent from `select_operator.py`. Or, if you want to go with `luci-interpreter`, the graphs are created by `tflchef with recipe.

**Comment by glistening** [comment] 2021-09-06 09:33
@jinevening or @mhs4670go 
> Yeap. @jinevening Is it okay for us to say luci-interpreter fully supports while op?

- Where can I find the testcase for `while` operator? It is likely to be a corresponding tflite recipe.

- How `luci-interpreter` is tested?

- Is there a way to create tflite recipe from existing `tflite`? Maybe `tflchef-rev`? How many operators does it cover?

**Comment by mhs4670go** [comment] 2021-09-06 11:06
> - Where can I find the testcase for `while` operator? It is likely to be a corresponding tflite recipe.

https://github.com/Samsung/ONE/blob/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-interpreter/src/kernels/While.test.cpp tests `while` op in a very simple way. And https://github.com/Samsung/ONE/blob/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-value-test/test.lst is the list of `luci-value-test`. Each test name is from https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/res/TensorFlowLiteRecipes. You can see `while` related tests there.

But as of now, `while` operator is disable in that list. @jinevening can help about it.

> - How `luci-interpreter` is tested?

Please see `*.test.cpp` files in  https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-interpreter/src/kernels. 

> - Is there a way to create tflite recipe from existing `tflite`? Maybe `tflchef-rev`? How many operators does it cover?

After building `compiler/tflchef`, you can use `build/compiler/tflchef/tools/reverse/tflchef-reverse`. Most of operators are supported as of now.

**Comment by glistening** [comment] 2021-09-06 12:10
> https://github.com/Samsung/ONE/blob/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-interpreter/src/kernels/While.test.cpp tests `while` op in a very simple way.

It's not a tflite recipe. It is a test written in C++.

> And https://github.com/Samsung/ONE/blob/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-value-test/test.lst is the list of `luci-value-test`. Each test name is from https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/res/TensorFlowLiteRecipes. You can see `while` related tests there.

All recipe seem to be a very simple with 1 operator.

> > * How `luci-interpreter` is tested?
> 
> Please see `*.test.cpp` files in https://github.com/Samsung/ONE/tree/3f7bc7c700c78e8fe7d4dbcc9757a31ea61dad69/compiler/luci-interpreter/src/kernels.

There is nothing to refer since they are written in c++.

> After building `compiler/tflchef`, you can use `build/compiler/tflchef/tools/reverse/tflchef-reverse`. Most of operators are supported as of now.

I think `tflchef-reverse` is the tool that we can use if we are enforced to prepare all test model with `tflchef`. I guess it will generate tflite recipe from existing tflite.

**Comment by glistening** [comment] 2021-09-06 14:01
@mhs4670go 

> There is no need to know about `TFLite recipe` to use only `circle-interpreter`. But, if you implement test related modules, you should. Because all the test resources in compiler is from the recipe.

- `circle-opselector` will select several nodes from given network. To test `circle-opselector` we plan to use some famous networks like `mobilenet` or `inception` and so son. But according to your guide, all test resources should come from the recipe. Do you mean we need to create tflite reciple corresponding to `mobilenet` or `inception` and so on?

- If so, can `tflchef-reverse` do this conversion? May I assume the converted recipes are valid? 

- Why `compiler` doesn't download the network and use `tflite` as it is? Why do we need to convert tflite to `tflite recipe`, and convert it back to `tflite`?

**Comment by glistening** [comment] 2021-09-06 14:57
Here are answers to my questions

> * If so, can `tflchef-reverse` do this conversion? 

Yes. I've confirmed `tflchef-reverse` succeeds to convert `inceptionv3.tflite`.

```
$ ./build/install/bin/tflchef-reverse inceptionv3.tflite inceptionv3.recipe
$ ls inceptionv3.*
-rw-rw-r-- 1 gyu gyu   132302 Sep  6 23:38 inceptionv3.recipe
-rw-rw-r-- 1 gyu gyu 95325648 Oct  2  2019 inceptionv3.tflite
```

> May I assume the converted recipes are valid?

I've confirmed `tflchef-file` succeed to convert it back to `tflite`.

```
$ ./build/install/bin/tflchef-file inceptionv3.recipe iv3.tflite
$ ls iv3.tflite
-rw-rw-r-- 1 gyu gyu 95335704 Sep  6 23:41 iv3.tflite
```

I can see the graph in `netron`.

Also, `model_parser.py` shows same summary for `inceptionv3.tflite` (original) and `iv3.tflite` (go to recipe, and back to tflite).

```
$ ./tools/tflitefile_tool/model_parser.py iv3.tflite
Number of all operator types: 6
        AVERAGE_POOL_2D                       :   10
        CONCATENATION                         :   15
        CONV_2D                               :   95
        MAX_POOL_2D                           :    4
        RESHAPE                               :    1
        SOFTMAX                               :    1
Number of all operators                       :  126

Expected TOTAL  memory: 146.6M
Expected FILLED memory: 90.9M
```

> * Why `compiler` doesn't download the network and use `tflite` as it is? Why do we need to convert tflite to `tflite recipe`, and convert it back to `tflite`?

At least, there are two reasons:
1. recipe uses less storage. ( 91 MB -> 130 K)
2. recipe is human-readable.

**Comment by kevin622** [comment] 2021-09-07 04:38
Wow! Thank you for showing such tremendous interest for our Issue. We admire your enthusiasm for our project. :smile:

Currently, we are planning to stick on the first option; using [`tflite2nnpkgtc`](https://github.com/Samsung/ONE/blob/master/tools/nnpackage_tool/sth2nnpkgtc/tflite2nnpkgtc.md). So the `circle_opselector.test.sh`(the name will probably change) that we are about to write will recieve a `tflite` file as input and the shell script will consist of __3 stages__. Since I've introduced the steps already above and @glistening gave us a great comment about it, this time I'll focus on the actual operations.

__<Usage>__
Assuming the test is done on `origin.tflite`.

```shell
$ circle_opselector.test.sh origin.tflite
```

__< Stages >__

1. Run [`select_operator.py`](https://github.com/Samsung/ONE/blob/master/tools/tflitefile_tool/select_operator.py) on `origin.tflite` with __random input__(random, but the range should be within the nodes of the model) to create a subgraph `trimmed.tflite`. 

   @mhs4670go pointed out that `select_operator.py` should not be included in the testing procedure, but since we are developing an operator that is fundamentally identical to `select_operator.py`, we thought the usage of this file is reasonable.

2. Run [`tflite2nnpckgtc.sh`](https://github.com/Samsung/ONE/blob/master/tools/nnpackage_tool/sth2nnpkgtc/tflite2nnpkgtc.sh) to create a __package__ of  `trimmed.tflite`. 
   The structure of the package folder will be as below.

```shell
trimmed
├── trimmed.tflite
└── metadata
    ├── MANIFEST
    └── tc
        ├── expected.h5
        └── input.h5
```

3. Create `origin.circle` by running [`tflite2circle`](https://github.com/Samsung/ONE/tree/master/compiler/tflite2circle) with input as `origin.tflite`.
4. Run `circle_opselector` to create `trimmed.circle`. The input of this operation(that is, the nodes to be selected) should be identical to the input of __stage 1__.
5. Switch the `trimmed.tflite` model in the package to a the `trimmed.circle` model. 
   Then the structure will be changed as below.

```shell
trimmed
├── trimmed.circle
└── metadata
    ├── MANIFEST
    └── tc
        ├── expected.h5
        └── input.h5
```

Also, the contents of the MANIFEST should be changed, informing that the package contains a `circle` model. Before anything is done, the content of the file is below.

```
{
  ...
  "models"      : [ "trimmed.tflite" ],
  "model-types" : [ "tflite" ]
}
```

This content will be changed as below.

```
{
  ...
  "models"      : [ "trimmed.circle" ],
  "model-types" : [ "circle" ]
}
```

6. Use `onert-test`(code is [here](https://github.com/Samsung/ONE/blob/master/tests/scripts/onert-test) and the usage is explained [here](https://github.com/Samsung/ONE/blob/master/tools/nnpackage_tool/sth2nnpkgtc/tflite2nnpkgtc.md)) to test the package. 
   Since `input.h5` and `expected.h5` in `trimmed/metadata/tc` is created using `trimmed.tflite`, running `onert-test` is comparing the output of running `trimmed.tflite` model in compiler to the output of running `trimmed.circle`  in runtime.



By typing `circle_opselector.test.sh origin.tflite` on CLI, we expect the stages above to be done automatically.

**Comment by m-bronnikov** [comment] 2021-09-08 14:46
Hi, @parkeunsang, sorry for a late response, but I think the simplest way to **run** circle model for now is usage of `circle-eval-driver`!
So, let you have the model with `2` (or any another value) inputs. 
1. You need to generate input as binary files. For example, random input could be generated with python:
```python
import numpy as np

INPUT_SHAPES = [(1, 249, 249, 3), (1, 344, 344, 32)]
INPUT_PREFIX = "input."
INPUT_DTYPE = np.float32

for idx, shape in enumerate(INPUT_SHAPES):
  data = np.random.randn(*shape).astype(INPUT_DTYPE)
  with open(INPUT_PREFIX + str(idx), 'wb') as binf:
    binf.write(data.tobytes('C'))
```
2. Launch `luci-eval-driver`:
```bash
./build/compiler/luci-eval-driver/luci_eval_driver model.circle 2 input. output.
```
args: model path, count of inputs, input prefix, output prefix
result: outputs as binary files and shapes as text file, for model with 3 outputs you will obtain 6 files: `output.0`, `output.1`, `output.2`, `output.0.shape`, `output.1.shape`, `output.2.shape`

After this steps, you can convert binary outputs to list of numpy arrays in python with:
```python
import numpy as np
import tempfile
from pathlib import Path
from os import path

output_file_prefix = 'output.'
datatype = np.float32

# list of outputs
outputs = []

pathlist = list(Path('.').glob(output_file_prefix + '*.shape'))

for shape_path in pathlist:
    # define shape of output
    with open(shape_path, 'r') as sf:
        shape = tuple(map(int, sf.read().split(',')))

    # read bin data to np array
    bin_path = shape_path.with_suffix('')
    with open(bin_path, 'rb') as binf:
        print(bin_path)
        tensor_data = np.frombuffer(binf.read(), dtype=datatype).reshape(shape)
        outputs.append(tensor_data)
```

**Comment by parkeunsang** [comment] 2021-09-09 04:35
@m-bronnikov Your solution helped a lot. Thank you!!
Specifically, It was very interesting to run multiple models on **one circle file**(has multiple inputs or outputs).

**Closed** 2021-09-27 00:34 UTC
