### ISSUE TITLE
[compiler] Support dynamic shape for reshape 

### ISSUE THREAD

**Issue by zetwhite** [Samsung/ONE#13927] opened 2024-09-04 05:02 UTC
* origin: https://github.com/Samsung/ONE/issues/13697 
* first try by @jongwonyang, https://github.com/Samsung/ONE/pull/13912 

While reviewing above PR, I think we need to make some consensus about  `reshape` shape inference rule. 
So, I make this issue to discuss details. 

I'd like to suggest below 2 things. If you have some free time, please take a look and leave any kind of comments! 

/cc @llFreetimell @jongwonyang @shs-park @seanshpark

**Comment by zetwhite** [comment] 2024-09-04 06:26
### Background 

There are two `shape`s in `CircleReshape` node.

  * From attribute `_new_shape`: [:link:](https://github.com/Samsung/ONE/blob/48fd493997348a7ddcb0eefbfd033c38c87e56fd/compiler/luci/lang/include/luci/IR/Nodes/CircleReshape.h#L60) => Hereafter, mark as `shape_from_attr` 
  * From input named `shape`: [:link:](https://github.com/Samsung/ONE/blob/48fd493997348a7ddcb0eefbfd033c38c87e56fd/compiler/luci/lang/include/luci/IR/Nodes/CircleReshape.h#L39-L40) => Hereafter, mark as `shape_from_input` 

* why? 
   * https://github.com/tensorflow/tensorflow/issues/45150
   * > In tf, [reshape](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/array_ops.cc?rgh-link-date=2020-11-27T00%3A48%3A48Z#L1368-L1376) op always have two inputs.
In the mlir converter, the tflite [reshape](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/ir/tfl_ops.td?rgh-link-date=2020-11-27T00%3A48%3A48Z#L2575-L2593) op indeed will always have two inputs.
In TOCO, we do not have such restriction, so during transformations, we may introduce reshape op without the shape tensor as inputs. 

* I tried to make several models with different TF versions : 
  * Using `tf==2.13.0`, Only `shape_from_input` exists
  * Using `tf==1.12.0`, Both `shape_from_input` and `shape_from_attr` exist
  * Some old models might have only `shape_from_attr` 

-------------------------------------------------------------------

#### Suggestion 1 

It is cumbersome to determine when to use `shape_from_attr` and when to use `shape_from_input`, while shape inferencing. 

So,  How about doing it like this?

1. Create a canonicalize pass that makes `reshape` node has always 2 inputs; to make `shape_from_input` can be always used. 
2. Use `shape_from_input` during shape inference

**Comment by zetwhite** [comment] 2024-09-04 07:00
### Suggestion 2 

About `reshape` node dynamic shape inference rules, I'm considering following rules. 

* Let's just forward `reshape/shape` into the `output_shape`. 
   * <sub> `reshape/shape` is a TensorShape - decided by a data of `CircleConst`  or a tensor from `CircleNode` </sub> 


* If `output_shape` has 'one unknown dim' and it is possible to infer the unknown dim, infer it. 
   * otherwise, just return the unknown dimensions as they are.

---------------------------------------------------------------
I think this rule is simple and we don't need discussions, But I leave it to ensure that we have a same understanding.

**Comment by zetwhite** [comment] 2024-09-04 07:14
> It is cumbersome to determine when to use shape_from_attr and when to use shape_from_input, while shape inferencing. 

@llFreetimell also suggest to follow tensorflow rules 

  * use `shape_from_attr` 
  * if `shape_from_attr` not exists, use `shape_from_inputs` 
  * refer / https://github.com/tensorflow/tensorflow/blob/2fe29379f6449d263b787eb636020fd81017b8bf/tensorflow/lite/kernels/reshape.cc#L137-L143  
  
I think this is also a good idea :) 

----------------------------------------------

BTW, other current shape inference use `shape_from_inputs`, and ignore `shape_from_attrs`. https://github.com/Samsung/ONE/blob/949661a604378a48dfefa221b4bee50057480c78/compiler/luci/service/src/CircleShapeInferenceRule.cpp#L1047

**Comment by llFreetimell** [comment] 2024-09-04 07:51
> @llFreetimell suggest to follow tensorflow rules

Due to my wrong comments, some misunderstanding is propagated 😅 
My suggestion was following :
- When `reshape/shape` is `CircleConst`
  - use `shape_by_input` & `output_shape` would be static
  - Example case : `reshape(input, [2, 3]), attr=[2,3] --> [2, 3]`
- When `reshape/shape` is `CircleNode`
  - use `shape_by_input` & `output_shape` would be dynamic
  - Example case : `reshape(input, shape_node) --> [?, ?, ?]`
- When `reshape/shape` does not exist
  - use `shape_by_attr` & `output_shape` would be static
  - Example case : `reshape(input) --> [shape_by_attr]`

---

For me, suggestion 1 and 2 are all fine :)
However, if suggestion 2 is selected, I hope that above modification is applied T.T

**Comment by jongwonyang** [comment] 2024-09-04 08:23
> * When `reshape/shape` does not exist

> For me, suggestion 1 and 2 are all fine :) However, if suggestion 2 is selected, I hope that above modification is applied T.T

I have a small question.

If my understanding below is correct, does this modification involve changing the base class of the `CircleReshape` node?

Current implementation always adds `shape_by_input` even it's not provided. (based on `shape_by_attr`)
https://github.com/Samsung/ONE/blob/949661a604378a48dfefa221b4bee50057480c78/compiler/luci/import/src/Nodes/CircleReshape.cpp#L77
The comment says it's because of the current requirement of the IR(`CircleReshape`).

I think it's because current `CircleReshape` node is based on `FixedArityNode`.
https://github.com/Samsung/ONE/blob/433edf9cb5f42230c601284d53cb3ac884790848/compiler/luci/lang/include/luci/IR/Nodes/CircleReshape.h#L31

**Comment by zetwhite** [comment] 2024-09-04 08:44
> Due to my wrong comments, some misunderstanding is propagated 😅

Ah, I misunderstood tensorflow codes :cry: Sorry for confusion 

> My suggestion was following : 

Thank you for detailed guide :) It looks good to me.

**Comment by llFreetimell** [comment] 2024-09-04 08:49
> does this modification involve changing the base class of the CircleReshape node?

Not at all :)

> Current implementation always adds shape_by_input even it's not provided. (based on shape_by_attr)

I missed this codes exist... thanks..!
@zetwhite doesn't it seems some kinds of canonicalization logic...?
If so, how about following re-suggestions?
- suggestion 1 with moving that logic from `luci/import` to canonicalize pass
- suggestion 2 with checking `reshape/shape` is `CircleOutputDummy` or not

**Comment by zetwhite** [comment] 2024-09-04 08:56
> @zetwhite doesn't it seems some kinds of canonicalization logic...? 

I think so. Hmm.. 
IMHO, moving to canonicalization is a bit out of scope, I think we could talk it later (or other issue). 

> Current implementation always adds shape_by_input even it's not provided. (based on shape_by_attr) 

I didn't know it two. thank you for figure it out :+1:  


If so, how about this? A bit modified version from @llFreetimell 

- make sure that `CircleReshape` has always `reshape/shape` -> otherwise, throw an error 
- When `reshape/shape` is `CircleConst`
  - use `shape_by_input` & `output_shape` would be static
  - Example case : `reshape(input, [2, 3]), attr=[2,3] --> [2, 3]`
- When `reshape/shape` is `CircleNode`
  - use `shape_by_input` & `output_shape` would be dynamic
  - Example case : `reshape(input, shape_node) --> [?, ?, ?]`
- When `reshape/shape` is `CircleOutputDummy` 
  - Throw an error

**Comment by llFreetimell** [comment] 2024-09-04 09:19
@zetwhite Looks nice :D I agree for your final suggestion!

**Comment by zetwhite** [comment] 2024-09-04 10:54
@jongwonyang Could you make a draft PR based on this discussion? 
If sth is ambiguous while working, please freely leave any comment here :)

**Comment by jongwonyang** [comment] 2024-09-04 11:05
> @jongwonyang Could you make a draft PR based on this discussion? If sth is ambiguous while working, please freely leave any comment here :)

Of course! I'll create the draft PR ASAP. The final suggestion looks good to me :)

Thank you for addressing this issue!

> +) I'll take a look this recipe ( [#13866 (comment)](https://github.com/Samsung/ONE/pull/13866#discussion_r1740255940) ) and try to fix it.

Thank you for this too :)

**Comment by jongwonyang** [comment] 2024-09-04 12:16
I have created the draft PR https://github.com/Samsung/ONE/pull/13935

**Comment by seanshpark** [comment] 2024-09-04 21:36
> When reshape/shape is CircleOutputDummy
>    reshape without shape might mean the graph is invalid -> so, let's throw an error in this case.

No. This is not invalid. We had a model like this. 
We should use `newShape` attribute.

**Comment by jongwonyang** [comment] 2024-09-05 04:35
> No. This is not invalid. We had a model like this. We should use `newShape` attribute.

Thanks for pointing out.

But the current `CircleReshapeGraphBuilder` creates `CircleOutputDummy` when there's no `shape_by_input` and no `shape_by_attr`.

https://github.com/Samsung/ONE/blob/487afbd5fd0d46bc835b0ed2aaba0a1dc62ee5ea/compiler/luci/import/src/Nodes/CircleReshape.cpp#L87

Could you give me some more detailed explanation about how to utilize `newShape` attribute in `CircleReshape`?

**Comment by seanshpark** [comment] 2024-09-05 04:54
> creates CircleOutputDummy when there's no shape_by_input and no shape_by_attr.

Can you please explain how to got this from the code ?

**Comment by zetwhite** [comment] 2024-09-05 06:05
> > creates CircleOutputDummy when there's no shape_by_input and no shape_by_attr.

> Can you please explain how to got this from the code ?

I guess it from the importer code. Is there a thing I missed?  

copy from [import/src/Nodes/CircleReshape.cpp](https://github.com/Samsung/ONE/blob/487afbd5fd0d46bc835b0ed2aaba0a1dc62ee5ea/compiler/luci/import/src/Nodes/CircleReshape.cpp#L77-L92) 

```cpp 
  auto *shape_node = (inputs.size() == 2) ? inputs.at(1) : nullptr;
  if (shape_node == nullptr) 
  {
    const auto *options = op.builtin_options.AsReshapeOptions();
    if (options != nullptr)
	{
	  // shape_node X, attribute O -> create input node based on attribute
      shape_node = create_shape_node(options->new_shape, graph);
	} 
    else
    { 
	  // shape_node X, attribute X -> create CircleOutputDummy 
	  // If CircleOutputDummy exist, it means that both shape_node and attribute are NOT exist 
      shape_node = graph->nodes()->create<CircleOutputDummy>();
      shape_node->dtype(loco::DataType::S32);
      shape_node->rank(0);
      shape_node->name("Reshape/dummy");
    }
  }
```

**Comment by zetwhite** [comment] 2024-09-05 06:27
+) Ah, Maybe this situation can happened. 

`luci/import` is used to load a circle file into memory.

If a circle file has a `CircleReshape (input = CircleDummy([]), attirbute=[1, 2, 3])`, `luci/import` might just pass it. 
So, `luci/pass` could meet "CircleDummy O, Attribute O" situation.

**Comment by llFreetimell** [comment] 2024-09-05 06:46
> If a circle file has a CircleReshape (input = CircleDummy, attirbute=[1, 2, 3]), luci/import might just pass it.
So, luci/pass could meet "CircleDummy O, Attribute O" situation.

Isn't `CircleReshape (input = CircleDummy, attirbute=[1, 2, 3])` equal to `shape_node X, attribute O` situation..?

**Comment by zetwhite** [comment] 2024-09-05 07:00
> Isn't CircleReshape (input = CircleDummy, attirbute=[1, 2, 3]) equal to shape_node X, attribute O situation..?

* `CircleReshape(shape_node X, attirbute O)` -> `luci/import` -> `CircleReshape(shape_node=CircleConst, attribute O)` 
   * shape_node will be generated base on attribute values 

* `CircleReshape(shape_node = CircleDummy, attirbute O)` -> `luci/import` -> `CircleReshape(shape_node = CircleDummy, attribute O)` 
	* reshape node with dummy input, but valid attribute might appeared

**Comment by seanshpark** [comment] 2024-09-05 07:08
I think the current `build()` code can give some confusion, and also my memories are also not clear.
Last related change is #1519 , where creation of CircleDummy was introduced.
We have #1554 as regression test, read/write and shape inference can be checked.

Not sure how to define valid/invalid models now, but we can have
- Reshape/shape O, attribute O
- Reshape/shape O, attribute X
- Reshape/shape X, attribute O

Not sure `Reshape/shape X, attribute X` can exist in real world.

As current `build()` logic can give misunderstandings, we could revise current implementation.

**Comment by zetwhite** [comment] 2024-09-05 07:56
> We have https://github.com/Samsung/ONE/pull/1554 as regression test, read/write and shape inference can be checked. 
> Not sure Reshape/shape X, attribute X can exist in real world. 

Thanks for information.

Since there is a recipe `Reshape/shape X, attribute X`, we have to decide how to handle this case. 

1. regard `Reshape X, attribute X` is a valid graph
	* while importing make `Reshape/shape = DummyCircle` 
	* while shape inferencing if `Reshape/shape = DummyCircle`, 
	  * try to shape inference using `attribute` 
	  * try to shape inference using `output_shape`
	  
3. regard `Reshape/shape X, attribute X` is an invalid graph 
   * remove `Reshape/shape X, attribute X` recipe
   * throw an error in `build()` graph, 
   * (also, throw an error in `shape inference`)

**Comment by seanshpark** [comment] 2024-09-05 08:00
> there is a recipe Reshape/shape X, attribute X

Can you give the recipe name?

**Comment by zetwhite** [comment] 2024-09-05 08:01
> Can you give the recipe name? 

I was considering this recipe. 

https://github.com/seanshpark/ONE/blob/ae0b9c5816dbc3a316e94a39797aae359078b846/res/TensorFlowLiteRecipes/Reshape_003/test.recipe

**Comment by seanshpark** [comment] 2024-09-05 08:04
From history, #1519 , we had a real world model for both X.

**Comment by glistening** [comment] 2024-09-05 08:28
I don't know the details and history of frontend compiler.

But you may refer to tflite's behavior.

https://github.com/tensorflow/tensorflow/blob/885b3d6a4091e5610a6b342e802e1850bd82a5e1/tensorflow/lite/kernels/reshape.cc#L145-L176

```cc
TfLiteStatus Prepare(TfLiteContext* context, TfLiteNode* node) {
  TF_LITE_ENSURE(context, NumInputs(node) == 1 || NumInputs(node) == 2);
  TF_LITE_ENSURE_EQ(context, NumOutputs(node), 1);
  OpData* op_data = reinterpret_cast<OpData*>(node->user_data);
  op_data->output_ptr = nullptr;

  // Always postpone sizing string tensors, even if we could in principle
  // calculate their shapes now. String tensors don't benefit from having their
  // shapes precalculated because the actual memory can only be allocated after
  // we know all the content.
  TfLiteTensor* output;
  TF_LITE_ENSURE_OK(context,
                    GetOutputSafe(context, node, kOutputTensor, &output));
  if (output->type != kTfLiteString) {
    const TfLiteTensor* input = GetInput(context, node, kInputTensor);
    const TfLiteTensor* shape = GetInput(context, node, kShapeTensor);
    if (NumInputs(node) == 1 || IsConstantOrPersistentTensor(shape)) {
      if (IsConstantOrPersistentTensor(input)) {
        SetTensorToPersistentRo(output);
        TF_LITE_ENSURE_OK(context, ResizeOutput(context, node));
        op_data->output_ptr = output->data.data;
        memcpy(output->data.data, input->data.data, input->bytes);
        return kTfLiteOk;
      } else {
        TF_LITE_ENSURE_OK(context, ResizeOutput(context, node));
      }
    } else {
      SetTensorToDynamic(output);
    }
  }
  return kTfLiteOk;
}
```

**Comment by jongwonyang** [comment] 2024-09-05 11:34
Sorry for the late response.

I completely misunderstood the role of `luci/import`. Apologies for the confusion.

Now, I have a better understanding of the implementation, taking into account the existence of `Reshape/shape` and `attribute`.

I'll be adding more details to the [draft PR](https://github.com/Samsung/ONE/issues/1519) soon.

Thanks again for your participation and the great discussions!

**Comment by jongwonyang** [comment] 2024-09-27 00:48
> From history, #1519 , we had a real world model for both X. But actually, comment says
> 
> > There is a model where shape input is not Constant
> 
> We can remove 003 and add 004 for non constant input, like simple `Add`.

About removing 003, do you mean completely deleting 003 or just excluding/commenting out 003?

**Comment by seanshpark** [comment] 2024-09-27 00:51
> About removing 003...

just commenting with some explanation comments will do.

**Comment by jongwonyang** [comment] 2024-10-04 03:48
Following cases (from https://github.com/Samsung/ONE/issues/13927#issuecomment-2328295368) have been implemented:
- When `reshape/shape` is `CircleConst` 
  - https://github.com/Samsung/ONE/pull/14037
  - https://github.com/Samsung/ONE/pull/14061
- When `reshape/shape` is `CircleNode`
  - https://github.com/Samsung/ONE/pull/14128
  - https://github.com/Samsung/ONE/pull/14139

Following case is not implemented since the problem has been resolved by removing Reshape_003 recipe.
- When `reshape/shape` is `CircleOutputDummy`
  - https://github.com/Samsung/ONE/pull/14113
  - https://github.com/Samsung/ONE/pull/14117

Remaining case could be introduced when there is any issue with `CircleOutputDummy`.

For now, dynamic shape inference of reshape works well!

Thanks for all of your support =)
Please feel free to comment any additional ideas if you have!

**Closed** 2024-10-05 03:06 UTC
Labels: SSAFY
