### ISSUE TITLE
[onert] How to bind NNFW CAPI with Python

### ISSUE THREAD

**Issue by blue4683** [Samsung/ONE#11487] opened 2023-09-06 02:34 UTC
Related #11368
 
# Overview

We are currently binding `runtime/onert/api/include/nnfw.h`(NNFW CAPI) with `Python` and almost finish binding `nnfw.h` as it is.

But, as we proceeded with Python binding, we found that we need to think about the binding method.

In `C++`, data can be accessed through a pointer, so processed data can be used even if it is not returned. So `C++` function only returns `NNFW_STATUS`. But, because of this situation, `Python` is hard to use the data processed by `C++`.

We do not fully understand `nnfw.h` so we may not know what `nnfw.h` does. So we are going to proceed with the binding in the direction ONE wants. So we want to discuss about this.

We thought of two ways of binding.

# Way 1

```cpp
// in C++, get input tensorinfo
NNFW_STATUS input_tensorinfo(uint32_t index)
{
    return nnfw_input_tensorinfo(session, index, &ti);
}
```

```python
# in Python, get input tensorinfo
state = session.input_tensorinfo(0)
if state != NNFW_STATUS.NNFW_STATUS_NO_ERROR:
    print('nnfw_input_tensorinfo error')
    return
```

The first is that `Python` only sends the data required for `C++` handling all data. When `Python` sends data to `C++`, `Python` receives `NNFW_STATUS` to verify that it worked properly. If processed data(input, output, …) should be used in Python, it should be imported using functions (`get_input`, `get_output`, …).

# Way 2

```cpp
// In C++, get input tensorinfo
nnfw_tensorinfo input_tensorinfo(uint32_t index, nnfw_tensorinfo ti)
{
    NNFW_STATUS state = nnfw_input_tensorinfo(session, index, &ti);
    if (state != NNFW_STATUS_NO_ERROR)
    {
        exit(1);
    }
    return ti;
}
```

```python
# In Python, get input tensorinfo
ti = nnfw_tensorinfo()
ti = session.input_tensorinfo(0, ti)
# Handle with processed ti in Python
input_elements = num_elems(ti)
input = [0.0] * input_elements
input = session.set_input(0, input, ti, input_elements)
```

The second way is to send the data processed in `C++` to `Python`, too. `C++` sends not `NNFW_STATUS`, but processed data through `C++` function. If the `C++` function returns an inappropriate `NNFW_STATUS`, `C++` handles the error.

# Finish

We would like to ask your opinion on which of the above two ways to proceed with binding. Or, you can recommend other methods.

**Comment by blue4683** [comment] 2023-09-06 03:15
# Way 3

It seems like we just found a way to automatically reflect the data processed in C++ into Python.
When data is sent from Python, the data processed by Python is reflected by receiving and processing the data's address (&variable) from C++.
We think this is a better way than Way 2.

**Comment by ragmani** [comment] 2023-09-06 06:07
To be honest, I still don't understand what exactly the problem is.

First of all, since you mentioned about pointers for data, I think it would be good to discuss pointers for data by separating them into 3 types.
1. Pointers for data created inside onert(ONE Runtime) and delivered to user, such as `session`, `number`
  -  `NNFW_STATUS nnfw_create_session(nnfw_session **session)`
  - `NNFW_STATUS nnfw_input_size(nnfw_session *session, uint32_t *number)`
2. Pointers for data created by user and delivered through NNFW API, such as `buffer` of inputs and outputs.
  - `NNFW_STATUS nnfw_set_input(nnfw_session *session, uint32_t index, NNFW_TYPE type, const void *buffer, size_t length);`
  - `NNFW_STATUS nnfw_set_output(nnfw_session *session, uint32_t index, NNFW_TYPE type, void *buffer, size_t length)`
3. Pointers for data available for both 1 and 2, such as `tensor_info`.
  - `NNFW_STATUS nnfw_set_input_tensorinfo(nnfw_session *session, uint32_t index, const nnfw_tensorinfo *tensor_info)`
  - `NNFW_STATUS nnfw_input_tensorinfo(nnfw_session *session, uint32_t index, nnfw_tensorinfo *tensor_info)`
  - `NNFW_STATUS nnfw_output_tensorinfo(nnfw_session *session, uint32_t index, nnfw_tensorinfo *tensor_info)`

Which type is the problem? only 3? Or 2 and 3?

**Comment by blue4683** [comment] 2023-09-06 06:30
Simply, we created an issue because we were curious about how it should be designed to work in `Python`.

Previously, there was no data synchronization between `Python` and `C++`, so we were worried about how to import processed data through the `C++` function into `Python`. This has been resolved in only-object. If the data type is `int` or `float`, the data is still not processed. One example is `NNFW_STATUS nnfw_input_size(nnfw_session *session, uint32_t *number)`.

How can we solve this?

**Comment by ragmani** [comment] 2023-09-06 07:08
I don't know much about pybind11.
But couldn't you bind buffers for `int` and `float` wrapped in a new data structure like `the NNFW_SESSION` you bound?

This is an example of binding the data buffers I found. I don't know if it will help.
https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#buffer-protocol

**Comment by blue4683** [comment] 2023-09-06 07:41
We also thought about that method.

```cpp

// In C++, get input size
PYBIND11_MAKE_OPAQUE(std::vector<uint32_t>)

// In NNFW_SESSION class
NNFW_STATUS input_size(std::vector<uint32_t> &number)
{
    return nnfw_input_size(session, number.data());
}

PYBIND11_MODULE(nnfw_api_pybind, m)
{
    // ...
    py::bind_vector<std::vector<uint32_t>>(m, "uint32_t_vector");
    // ...
}
```

```python

# In Python, get input size
size = uint32_t_vector([0])
print(size[0])
state = session.input_size(size)
if state != NNFW_STATUS.NNFW_STATUS_NO_ERROR:
    print('input_size error')
    return
print(size[0])

>> 0
1
```

We put `int` or `float` in `vector` and confirmed that it can be changed. However, in order to access it in Python, users have to access it through an index on the list. We didn't apply it because we thought this process was uncomfortable.

Shall we proceed this way?

**Comment by ragmani** [comment] 2023-09-06 08:16
> We put int or float in vector and confirmed that it can be changed. However, in order to access it in Python, users have to access it through an index on the list. We didn't apply it because we thought this process was uncomfortable.
> Shall we proceed this way?

I think it would be better to provide our bound Python modules that Python users can use the modules more conveniently.
For example, I don't think it's necessary to provide status information to Python users. Perhaps just printing an error message would be enough.
Anyway, I think it would be good to refer to [tensorflow lite interpreter](https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter) for considering our modules to be more convenient.
And we will have no option other than index to access data for now since we don't provide the signature feature of tensorflow lite.

@Samsung/one_onert Please give SSAFY friends your opinion on the design.

@blue4683 Could you create a draft PR to reference so that we can facilitate our ongoing discussions?

**Comment by blue4683** [comment] 2023-09-06 08:24
OK!! I will create a draft PR ASAP.

**Comment by glistening** [comment] 2023-09-06 11:18
Here is my personal opinion.

I did not imagine our python API is a translation of c++.
I expected it will be defined in more pythonic way. For example, 

- Introduce module like `nnfw`.
- `Session` will be in `nnfw`. That is `nnfw.Session`.
- Session will be defined in `nnfw.Session`.
- Any error will be handled by exception, not by return value for every statement.
...

**Comment by blue4683** [comment] 2023-09-06 23:59
> Here is my personal opinion.
> 
> I did not imagine our python API is a translation of C API. I expected it will be defined in more pythonic way. For example,
> 
> * Introduce module like `nnfw`.
> * `Session` will be in `nnfw`. That is `nnfw.Session`.
> * Any error will be handled by exception, not by checking return value for every statement.
>   ...

Thank you for your opinion!!

We think we should also make Python API more pythonic.
So, plz let us know if the more pythonic method we thought is right with what you thought.

- Except for basic exception processing in C++ functions, exception processing according to status code(`NNFW_STATUS`) is handled in C++.
- Even if it does not return from the C++ functions, the Python data must be changed as handled by the function.

Plz let us know continuously if there is anything to consider while binding.

We also have a question.
- Should all enumerated, structure variables declared in nnfw.h be implemented in Python?

**Comment by ragmani** [comment] 2023-09-07 05:32
> Except for basic exception processing in C++ functions, exception processing according to status code(NNFW_STATUS) is handled in C++.

Now I understand what the problem is. The problem is that error handling cannot be handled outside of the API, so the only information available for error handling is status code (`NNFW_STATUS`).
I guess there are two options.
1. You handle errors using only the status code (`NNFW_STATUS`).
2. You implement C++ code that wraps internal code and bind that C++ code.
@Samsung/one_onert  Is it okay to bind internal code instead of NNFW CAPI?


> Even if it does not return from the C++ functions, the Python data must be changed as handled by the function.

Sorry. I don't understand what the problem is.

> Should all enumerated, structure variables declared in nnfw.h be implemented in Python?

There is no need to implement enumerators and structures in Python to provide them to users. But whether enumerators and structures are implemented internally in python may vary depending on your implementation using pybind11.
For example, to provide users with `NNFW_TYPE`, which represents data types, you can use a way that uses numpy array that contains data type information like [tensorflow lite interpreter](https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter).

**Comment by glistening** [comment] 2023-09-07 05:38
I don't have detail idea or guide for you at this moment.

You can get rough idea from other examples, which provides both C and Python API.
(e.g.`h5py`[^1], `tflite`, ...)

Also, please keep in mind that the goal is to provide interface which is easy to use in python.

> - Should all enumerated, structure variables declared in nnfw.h be implemented in Python?

I guess there is no simple rule can be done in mechanical way.

For example, h5py `File` gets [several parameters](https://docs.h5py.org/en/stable/high/file.html#reference). But not all parameters are defined as enumerator, some of them is just string. It is easy to development and use, but it may lead to hard-to-debug. I guess there are several preference for each people. For me, both are ok at this moment.

Also, your PR will be in experimental API. Please go ahead, I am pleased you're doing well. : )

[^1]: [H5Py frontpage](https://docs.h5py.org/en/stable/index.html) says "_The h5py package is a Pythonic interface to the HDF5 binary data format._".

**Comment by blue4683** [comment] 2023-09-07 06:37
> > Even if it does not return from the C++ functions, the Python data must be changed as handled by the function.
> 
> Sorry. I don't understand what the problem is.

We think this is an opinion that We don't have to think about anymore.
It was about data synchronization between `Python` and `C++`. But, if we bind pythonically, we would have to return the processed data from `C++` to `Python`.

Thank you for your answer!

**Comment by blue4683** [comment] 2023-09-07 06:44
> Also, please keep in mind that the goal is to provide interface which is easy to use in python.

Then we will proceed with the goal that users can easily use `nnfw.h` through the `Python API`.



> For example, h5py `File` gets [several parameters](https://docs.h5py.org/en/stable/high/file.html#reference). But not all parameters are defined as enumerator, some of them is just string. It is easy to develop and use, but it may lead to hard-to-debug. I guess there are several preference for each people. For me, both are ok at this moment.

We understood which direction to bind.
We will try to implement a pythonic API by referring to the examples you have informed us.

> Also, your PR will be in experimental API. Please go ahead, I am pleased you're doing well. : )

Thank you for the positive feedback and we will do our best. :)

**Comment by ragmani** [comment] 2023-09-12 11:46
> I guess there are two options.
> 1. You handle errors using only the status code (`NNFW_STATUS`).
> 2. You implement C++ code that wraps internal code and bind that C++ code.
> @Samsung/one_onert  Is it okay to bind internal code instead of NNFW CAPI?

Sorry for the late response. You have to bind NNFW CAPI because internal code can be changed later. Maybe you're already doing that, but I'm telling you this just in case you don't know.

**Comment by ragmani** [comment] 2023-09-12 11:49
> I guess there are two options.
> 1. You handle errors using only the status code (`NNFW_STATUS`).
> 2. You implement C++ code that wraps internal code and bind that C++ code.
> @Samsung/one_onert  Is it okay to bind internal code instead of NNFW CAPI?

Sorry for the late response. You have to bind NNFW CAPI because internal code may be changed later. Maybe you're already doing that, but I'm telling you this just in case you don't know.

**Comment by blue4683** [comment] 2023-09-18 04:32
We create Draft PR for binding nnfw.h with python.

plz check this PR and give your opinion!!

**Closed** 2023-10-11 01:19 UTC
Labels: type/discussion, SSAFY
