### ISSUE TITLE
[one-cmds] test failed

### ISSUE THREAD

**Issue by mhs4670go** [Samsung/ONE#7962] opened 2021-11-10 04:39 UTC
## What

http://npuci.mooo.com:8080/job/nnfw/job/master/job/push-nnpackage-test/581/console

`one-cmds` test failed. ~~I think #7924 is the problem.~~

**Comment by mhs4670go** [comment] 2021-11-10 04:40
```bash
/home/seongwoo/ONE/build/install/bin/venv/lib/python3.6/site-packages/tensorflow_addons/utils/ensure_tf_install.py:67: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.4.0 and strictly below 2.7.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.3.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
circle2circle: Failed to open file: inception_v3.circle
```

**Comment by mhs4670go** [comment] 2021-11-10 04:44
@binarman I'm gonna revert the PR(#7924) because of code freeze and then re-post the PR after fix it.

**Comment by chunseoklee** [comment] 2021-11-10 04:47
FYI, on CI side, onecc fail start with the 3 changes : 

```
[luci/import] Use direct access for inputs, outputs and name (#7947) (commit: 430bb00) (details)
[luci/import] Add opcode_name and builtin_code definitions (#7949) (commit: 5656590) (details)
[luci/import] Use direct access for metadata (#7950) (commit: cdace72) (details)

```

**Comment by seanshpark** [comment] 2021-11-10 05:05
`The versions of TensorFlow you are currently using is 2.3.0 and is not supported. ` message is shown for other normal cases. this may not be related with test failures.

**Comment by mhs4670go** [comment] 2021-11-10 05:06
It turns out `Use direct-access~` PRs seems a problem. Let's revert them and come up with a solution.

**Comment by seanshpark** [comment] 2021-11-10 05:13
@m-bronnikov , FYI failed test are described at https://github.com/Samsung/ONE/blob/master/compiler/one-cmds/tests/README.txt. these test are executed on daily bases as they take some time.
To perform a local test, make a installation with `./nncc build install` and then follow README.

**Comment by seanshpark** [comment] 2021-11-10 05:15
If the problem is fixed, https://github.com/Samsung/ONE/issues/7926 issue should close by itself (by git-bot-sec)

**Comment by m-bronnikov** [comment] 2021-11-10 14:09
I checkout to https://github.com/Samsung/ONE/commit/3f09806e1861e39ad290fd67ad5a7842f0df7d15 and dropped #7924. All test passed well.

<details>
<summary> Log </summary>

```
/usr/local$ sudo ./test/runtestall.sh 
one-build_001.test SUCCESS
one-build_002.test SUCCESS
one-build_003.test SUCCESS
one-build_004.test SUCCESS
one-build_005.test SUCCESS
one-build_006.test SUCCESS
one-build_007.test SUCCESS
one-build_008.test SUCCESS
one-build_009.test SUCCESS
one-build_010.test SUCCESS
one-build_011.test SUCCESS
one-build_012.test SUCCESS
one-build_013.test SUCCESS
one-build_014.test SUCCESS
one-build_neg_001.test SUCCESS
one-build_neg_002.test SUCCESS
one-build_neg_003.test SUCCESS
one-build_neg_004.test SUCCESS
one-build_neg_005.test SUCCESS
one-build_neg_006.test SUCCESS
one-build_neg_007.test SUCCESS
one-build_neg_008.test SUCCESS
one-build_neg_009.test SUCCESS
one-codegen_001.test SUCCESS
one-codegen_002.test SUCCESS
one-codegen_003.test SUCCESS
one-codegen_004.test SUCCESS
one-codegen_neg_001.test SUCCESS
one-import-bcq_001.test SUCCESS
one-import-bcq_neg_001.test SUCCESS
one-import-bcq_neg_002.test SUCCESS
one-import-bcq_neg_003.test SUCCESS
one-import-bcq_neg_004.test SUCCESS
one-import-bcq_neg_005.test SUCCESS
one-import-bcq_neg_006.test SUCCESS
one-import-bcq_neg_007.test SUCCESS
one-import-bcq_neg_008.test SUCCESS
one-import-bcq_neg_009.test SUCCESS
one-import-onnx_001.test SUCCESS
one-import_001.test SUCCESS
one-import_002.test SUCCESS
one-import_003.test SUCCESS
one-import_004.test SUCCESS
one-import_005.test SUCCESS
one-import_006.test SUCCESS
one-import_neg_001.test SUCCESS
one-import_neg_002.test SUCCESS
one-import_neg_003.test SUCCESS
one-import_neg_004.test SUCCESS
one-import_neg_005.test SUCCESS
one-import_neg_006.test SUCCESS
one-import_neg_007.test SUCCESS
one-import_neg_008.test SUCCESS
one-import_neg_009.test SUCCESS
one-import_neg_010.test SUCCESS
one-optimize_001.test SUCCESS
one-optimize_002.test SUCCESS
one-optimize_neg_001.test SUCCESS
one-optimize_neg_002.test SUCCESS
one-optimize_neg_003.test SUCCESS
one-optimize_neg_004.test SUCCESS
one-pack_001.test SUCCESS
one-pack_neg_001.test SUCCESS
one-pack_neg_002.test SUCCESS
one-pack_neg_003.test SUCCESS
one-profile_001.test SUCCESS
one-profile_002.test SUCCESS
one-profile_003.test SUCCESS
one-profile_004.test SUCCESS
one-profile_neg_001.test SUCCESS
one-quantize_001.test SUCCESS
one-quantize_002.test SUCCESS
one-quantize_003.test SUCCESS
one-quantize_004.test SUCCESS
one-quantize_005.test SUCCESS
one-quantize_006.test SUCCESS
one-quantize_007.test SUCCESS
one-quantize_008.test SUCCESS
one-quantize_neg_001.test SUCCESS
one-quantize_neg_002.test SUCCESS
one-quantize_neg_003.test SUCCESS
one-quantize_neg_004.test SUCCESS
one-quantize_neg_005.test SUCCESS
one-quantize_neg_006.test SUCCESS
one-quantize_neg_007.test SUCCESS
one-quantize_neg_008.test SUCCESS
one-quantize_neg_009.test SUCCESS
one-quantize_neg_010.test SUCCESS
one-quantize_neg_011.test SUCCESS
one-quantize_neg_012.test SUCCESS
one-quantize_neg_013.test SUCCESS
one-quantize_neg_014.test SUCCESS
one-quantize_neg_015.test SUCCESS
one-quantize_neg_016.test SUCCESS
one-quantize_neg_017.test SUCCESS
one-quantize_neg_018.test SUCCESS
one-quantize_neg_019.test SUCCESS
onecc_001.test SUCCESS
onecc_002.test SUCCESS
onecc_003.test SUCCESS
onecc_004.test SUCCESS
onecc_005.test SUCCESS
onecc_006.test SUCCESS
onecc_007.test SUCCESS
onecc_008.test SUCCESS
onecc_009.test SUCCESS
onecc_010.test SUCCESS
onecc_011.test SUCCESS
onecc_012.test SUCCESS
onecc_013.test SUCCESS
onecc_014.test SUCCESS
onecc_015.test SUCCESS
onecc_016.test SUCCESS
onecc_017.test SUCCESS
onecc_018.test SUCCESS
onecc_019.test SUCCESS
onecc_020.test SUCCESS
onecc_021.test SUCCESS
onecc_022.test SUCCESS
onecc_023.test SUCCESS
onecc_neg_001.test SUCCESS
onecc_neg_002.test SUCCESS
onecc_neg_003.test SUCCESS
onecc_neg_004.test SUCCESS
onecc_neg_005.test SUCCESS
onecc_neg_006.test SUCCESS
onecc_neg_007.test SUCCESS
onecc_neg_008.test SUCCESS
rawdata2hdf5_001.test SUCCESS
rawdata2hdf5_neg_001.test SUCCESS
rawdata2hdf5_neg_002.test SUCCESS
rawdata2hdf5_neg_003.test SUCCESS
rawdata2hdf5_neg_004.test SUCCESS
ALL TESTS PASSED!
```

</details>

I tried to launch `one-build_001` test with included #7924:

```
[one-build]
one-import-tf=True
one-import-tflite=False
one-import-bcq=False
one-optimize=True
one-quantize=False
one-pack=False
one-codegen=False

[one-import-tf]
input_path=inception_v3.pb
output_path=inception_v3.circle
input_arrays=input
input_shapes=1,299,299,3
output_arrays=InceptionV3/Predictions/Reshape_1
converter_version=v2

[one-optimize]
input_path=inception_v3.circle
output_path=inception_v3.opt.circle
```

 but looks like `one-optimize` starts earlier than `one-imort-tf` finishes work, so, error described in https://github.com/Samsung/ONE/issues/7962#issuecomment-964780985 occurs due to `inception_v3.circle` is not exist when `one-optimize` starts.



> It turns out `Use direct-access~` PRs seems a problem. Let's revert them and come up with a solution.

So, I think the reason is not direct-access related changes.

**Comment by mhs4670go** [comment] 2021-11-11 04:40
@m-bronnikov Thank you for your investigation. Please understand me doing lack of debugging, I was in a hurry for due date.

Now, let me do some investigation.

I started debugging from `4970e6ef28fed2cf001e9299ace64b8ecd1f4e49`.

First, I cherry-picked `c0c216943a795903633241ee70c9e961a611f5cd`. 
```bash
# c0c216943a795903633241ee70c9e961a611f5cd
Author: Alexander Efimov <efimov.alexander@gmail.com>
Date:   Tue Nov 9 13:29:24 2021 +0300

    [one-cmds] Auto detect drivers (#7924)
    
    This PR introduces mechanism for auto detecting available drivers.
    
    ONE-DCO-1.0-Signed-off-by: Alexander Efimov <a.efimov@samsung.com>
```
And, ran `runtestall.sh`.

<details>
<summary> runtestall.sh </summary>

```
$ ./runtestall.sh
one-build_001.test FAILED
one-build_002.test FAILED
one-build_003.test FAILED
one-build_004.test FAILED
one-build_005.test FAILED
one-build_006.test FAILED
one-build_007.test FAILED
one-build_008.test FAILED
one-build_009.test FAILED
one-build_010.test FAILED
one-build_011.test FAILED
one-build_012.test FAILED
one-build_013.test FAILED
one-build_014.test FAILED
one-build_neg_001.test SUCCESS
one-build_neg_002.test FAILED
one-build_neg_003.test SUCCESS
one-build_neg_004.test SUCCESS
one-build_neg_005.test FAILED
one-build_neg_006.test FAILED
one-build_neg_007.test SUCCESS
one-build_neg_008.test SUCCESS
one-build_neg_009.test SUCCESS
one-codegen_001.test SUCCESS
one-codegen_002.test SUCCESS
one-codegen_003.test SUCCESS
one-codegen_004.test SUCCESS
one-codegen_neg_001.test SUCCESS
one-import-bcq_001.test SUCCESS
one-import-bcq_neg_001.test SUCCESS
one-import-bcq_neg_002.test SUCCESS
one-import-bcq_neg_003.test SUCCESS
one-import-bcq_neg_004.test SUCCESS
one-import-bcq_neg_005.test SUCCESS
one-import-bcq_neg_006.test SUCCESS
one-import-bcq_neg_007.test SUCCESS
one-import-bcq_neg_008.test SUCCESS
one-import-bcq_neg_009.test SUCCESS
one-import-onnx_001.test SUCCESS
one-import_001.test SUCCESS
one-import_002.test SUCCESS
one-import_003.test SUCCESS
one-import_004.test SUCCESS
one-import_005.test SUCCESS
one-import_006.test SUCCESS
one-import_neg_001.test SUCCESS
one-import_neg_002.test SUCCESS
one-import_neg_003.test SUCCESS
one-import_neg_004.test SUCCESS
one-import_neg_005.test SUCCESS
one-import_neg_006.test SUCCESS
one-import_neg_007.test SUCCESS
one-import_neg_008.test SUCCESS
one-import_neg_009.test SUCCESS
one-import_neg_010.test SUCCESS
one-optimize_001.test SUCCESS
one-optimize_002.test SUCCESS
one-optimize_neg_001.test SUCCESS
one-optimize_neg_002.test SUCCESS
one-optimize_neg_003.test SUCCESS
one-optimize_neg_004.test SUCCESS
one-pack_001.test SUCCESS
one-pack_neg_001.test SUCCESS
one-pack_neg_002.test SUCCESS
one-pack_neg_003.test SUCCESS
one-profile_001.test SUCCESS
one-profile_002.test SUCCESS
one-profile_003.test SUCCESS
one-profile_004.test SUCCESS
one-profile_neg_001.test SUCCESS
one-quantize_001.test FAILED
one-quantize_002.test SUCCESS
one-quantize_003.test SUCCESS
one-quantize_004.test SUCCESS
one-quantize_005.test SUCCESS
one-quantize_006.test SUCCESS
one-quantize_007.test SUCCESS
one-quantize_008.test SUCCESS
one-quantize_neg_001.test SUCCESS
one-quantize_neg_002.test SUCCESS
one-quantize_neg_003.test SUCCESS
one-quantize_neg_004.test FAILED
one-quantize_neg_005.test SUCCESS
one-quantize_neg_006.test SUCCESS
one-quantize_neg_007.test SUCCESS
one-quantize_neg_008.test SUCCESS
one-quantize_neg_009.test FAILED
one-quantize_neg_010.test FAILED
one-quantize_neg_011.test FAILED
one-quantize_neg_012.test FAILED
one-quantize_neg_013.test SUCCESS
one-quantize_neg_014.test SUCCESS
one-quantize_neg_015.test SUCCESS
one-quantize_neg_016.test SUCCESS
one-quantize_neg_017.test SUCCESS
one-quantize_neg_018.test SUCCESS
one-quantize_neg_019.test SUCCESS
onecc_001.test FAILED
onecc_002.test FAILED
onecc_003.test FAILED
onecc_004.test FAILED
onecc_005.test FAILED
onecc_006.test FAILED
onecc_007.test FAILED
onecc_008.test FAILED
onecc_009.test FAILED
onecc_010.test FAILED
onecc_011.test FAILED
onecc_012.test FAILED
onecc_013.test SUCCESS
onecc_014.test SUCCESS
onecc_015.test SUCCESS
onecc_016.test SUCCESS
onecc_017.test SUCCESS
onecc_018.test FAILED
onecc_019.test ERROR: Missing inputfile
onecc_019.test FAILED
onecc_020.test SUCCESS
onecc_021.test FAILED
onecc_022.test FAILED
onecc_023.test FAILED
onecc_neg_001.test SUCCESS
onecc_neg_002.test FAILED
onecc_neg_003.test SUCCESS
onecc_neg_004.test SUCCESS
onecc_neg_005.test FAILED
onecc_neg_006.test FAILED
onecc_neg_007.test SUCCESS
onecc_neg_008.test SUCCESS
rawdata2hdf5_001.test SUCCESS
rawdata2hdf5_neg_001.test SUCCESS
rawdata2hdf5_neg_002.test SUCCESS
rawdata2hdf5_neg_003.test SUCCESS
rawdata2hdf5_neg_004.test SUCCESS
43 TESTS FAILED
```

</details>

The reason why the test failed is because drivers weren't run in a right order.
> But looks like `one-optimize` starts earlier than `one-imort-tf` finishes work. Error described in https://github.com/Samsung/ONE/issues/7962#issuecomment-964780985 occurs due to `inception_v3.circle` is not exist when `one-optimize` starts.

 As @m-bronnikov said, `one-build` makes the sequence of drivers and then run them.
```python
drivers = [
        'one-import-tf', 'one-import-tflite', 'one-import-bcq', 'one-import-onnx',
        'one-optimize', 'one-quantize', 'one-pack', 'one-codegen'
    ]
..
    # get sections to run
    section_to_run = []
    for d in drivers:
        if _is_available_driver(config, d):
            section_to_run.append(d)
```

**Comment by mhs4670go** [comment] 2021-11-11 05:19
@m-bronnikov 

I started from 75a361627 and this commit passed all the tests.

First, I checkouted to 430bb00ff. 

<details>
<summary> runtestall.sh </summary>

one-build_001.test SUCCESS
one-build_002.test SUCCESS
one-build_003.test SUCCESS
one-build_004.test SUCCESS
one-build_005.test FAILED
one-build_006.test SUCCESS
one-build_007.test SUCCESS
one-build_008.test SUCCESS
one-build_009.test SUCCESS
one-build_010.test SUCCESS
one-build_011.test SUCCESS
one-build_012.test SUCCESS
one-build_013.test SUCCESS
one-build_014.test SUCCESS
one-build_neg_001.test SUCCESS
one-build_neg_002.test SUCCESS
one-build_neg_003.test SUCCESS
one-build_neg_004.test SUCCESS
one-build_neg_005.test SUCCESS
one-build_neg_006.test SUCCESS
one-build_neg_007.test SUCCESS
one-build_neg_008.test SUCCESS
one-build_neg_009.test SUCCESS
one-codegen_001.test SUCCESS
one-codegen_002.test SUCCESS
one-codegen_003.test SUCCESS
one-codegen_004.test SUCCESS
one-codegen_neg_001.test SUCCESS
one-import-bcq_001.test SUCCESS
one-import-bcq_neg_001.test SUCCESS
one-import-bcq_neg_002.test SUCCESS
one-import-bcq_neg_003.test SUCCESS
one-import-bcq_neg_004.test SUCCESS
one-import-bcq_neg_005.test SUCCESS
one-import-bcq_neg_006.test SUCCESS
one-import-bcq_neg_007.test SUCCESS
one-import-bcq_neg_008.test SUCCESS
one-import-bcq_neg_009.test SUCCESS
one-import-onnx_001.test SUCCESS
one-import_001.test SUCCESS
one-import_002.test SUCCESS
one-import_003.test SUCCESS
one-import_004.test SUCCESS
one-import_005.test SUCCESS
one-import_006.test SUCCESS
one-import_neg_001.test SUCCESS
one-import_neg_002.test SUCCESS
one-import_neg_003.test SUCCESS
one-import_neg_004.test SUCCESS
one-import_neg_005.test SUCCESS
one-import_neg_006.test SUCCESS
one-import_neg_007.test SUCCESS
one-import_neg_008.test SUCCESS
one-import_neg_009.test SUCCESS
one-import_neg_010.test SUCCESS
one-optimize_001.test SUCCESS
one-optimize_002.test SUCCESS
one-optimize_neg_001.test SUCCESS
one-optimize_neg_002.test SUCCESS
one-optimize_neg_003.test SUCCESS
one-optimize_neg_004.test SUCCESS
one-pack_001.test SUCCESS
one-pack_neg_001.test SUCCESS
one-pack_neg_002.test SUCCESS
one-pack_neg_003.test SUCCESS
one-profile_001.test SUCCESS
one-profile_002.test SUCCESS
one-profile_003.test SUCCESS
one-profile_004.test SUCCESS
one-profile_neg_001.test SUCCESS
one-quantize_001.test SUCCESS
one-quantize_002.test SUCCESS
one-quantize_003.test SUCCESS
one-quantize_004.test SUCCESS
one-quantize_005.test SUCCESS
one-quantize_006.test SUCCESS
one-quantize_007.test SUCCESS
one-quantize_008.test SUCCESS
one-quantize_neg_001.test SUCCESS
one-quantize_neg_002.test SUCCESS
one-quantize_neg_003.test SUCCESS
one-quantize_neg_004.test SUCCESS
one-quantize_neg_005.test SUCCESS
one-quantize_neg_006.test SUCCESS
one-quantize_neg_007.test SUCCESS
one-quantize_neg_008.test SUCCESS
one-quantize_neg_009.test SUCCESS
one-quantize_neg_010.test SUCCESS
one-quantize_neg_011.test SUCCESS
one-quantize_neg_012.test SUCCESS
one-quantize_neg_013.test SUCCESS
one-quantize_neg_014.test SUCCESS
one-quantize_neg_015.test SUCCESS
one-quantize_neg_016.test SUCCESS
one-quantize_neg_017.test SUCCESS
one-quantize_neg_018.test SUCCESS
one-quantize_neg_019.test SUCCESS
onecc_001.test SUCCESS
onecc_002.test SUCCESS
onecc_003.test SUCCESS
onecc_004.test SUCCESS
onecc_005.test FAILED
onecc_006.test SUCCESS
onecc_007.test SUCCESS
onecc_008.test SUCCESS
onecc_009.test SUCCESS
onecc_010.test SUCCESS
onecc_011.test SUCCESS
onecc_012.test SUCCESS
onecc_013.test SUCCESS
onecc_014.test SUCCESS
onecc_015.test SUCCESS
onecc_016.test SUCCESS
onecc_017.test FAILED
onecc_018.test FAILED
onecc_019.test ERROR: Missing inputfile
onecc_019.test FAILED
onecc_020.test SUCCESS
onecc_021.test SUCCESS
onecc_022.test SUCCESS
onecc_023.test FAILED
onecc_neg_001.test SUCCESS
onecc_neg_002.test SUCCESS
onecc_neg_003.test SUCCESS
onecc_neg_004.test SUCCESS
onecc_neg_005.test SUCCESS
onecc_neg_006.test SUCCESS
onecc_neg_007.test SUCCESS
onecc_neg_008.test SUCCESS
rawdata2hdf5_001.test SUCCESS
rawdata2hdf5_neg_001.test SUCCESS
rawdata2hdf5_neg_002.test SUCCESS
rawdata2hdf5_neg_003.test SUCCESS
rawdata2hdf5_neg_004.test SUCCESS
6 TESTS FAILED

</details>
@m-bronnikov Maybe more commits are needed? 

(TO BE CONTINUE..)

**Comment by m-bronnikov** [comment] 2021-11-11 05:20
> As @m-bronnikov said, `one-build` makes the sequence of drivers and then run them.
> 
> ```python
> drivers = [
>         'one-import-tf', 'one-import-tflite', 'one-import-bcq', 'one-import-onnx',
>         'one-optimize', 'one-quantize', 'one-pack', 'one-codegen'
>     ]
> ..
>     # get sections to run
>     section_to_run = []
>     for d in drivers:
>         if _is_available_driver(config, d):
>             section_to_run.append(d)
> ```

I think sorting of found drivers in right order before execution could fix #7924.

**Comment by m-bronnikov** [comment] 2021-11-11 05:26
@mhs4670go Could you please test starting from https://github.com/Samsung/ONE/commit/4338bade299ca97636e96779add2e6b68dc03e24 becasue I did error in `native_name` method and fix ot with this commit?

**Comment by m-bronnikov** [comment] 2021-11-11 05:27
@mhs4670go Could you please test starting from https://github.com/Samsung/ONE/commit/4338bade299ca97636e96779add2e6b68dc03e24 becasue I did error in `native_name` method and fix ot with this commit?

**Comment by mhs4670go** [comment] 2021-11-11 06:04
@m-bronnikov 

I started from 4f7c1d1245714faa308742e1f91b0790beee0d2d(without c0c216943a795903633241ee70c9e961a611f5cd).

And I ran the tests per every commit.
4f7c1d1245714faa308742e1f91b0790beee0d2d
3f09806e1861e39ad290fd67ad5a7842f0df7d15

And, it all passed. I think fixing #7924 will do the trick. Sorry for bothering you.

**Comment by seanshpark** [comment] 2021-11-24 03:13
can we close this?

**Closed** 2021-12-08 06:10 UTC
Labels: type/issue
